kind: pipeline
name: default
trigger:
  branch:
    - main
  event:
    - push
workspace:
  path: /drone/src

environment:
  REPO_NAME: web-installer
  IMAGE_NAME: web-installer
  REGISTRY_SERVER_NAME: registry.format.hu

steps:
  - name: build image
    image: plugins/docker
    commands:
      - cd /drone/src/
      - docker build --platform linux/amd64,linux/arm64 -t $${REGISTRY_SERVER_NAME}/$${IMAGE_NAME} -f Dockerfile .
      - docker push $${REGISTRY_SERVER_NAME}/$${IMAGE_NAME}
    when:
      branch:
        - main
    volumes:
      - name: docker
        path: /var/run/docker.sock
 
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
