kind: pipeline
name: default
trigger:
  branch:
    - main
  event:
    - push
workspace:
  path: /drone/src

environment:
  REPO_NAME: web-installer
  IMAGE_NAME: web-installer
  REGISTRY_SERVER_NAME: registry.format.hu
  DOCKER_REGISTRY_URL: registry.format.hu

steps:
  - name: build image
    image: plugins/docker
    commands:
      - cd /drone/src/
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - docker build --platform linux/aarch64 --tag $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/aarch64 -f Dockerfile .
      - docker build --platform linux/amd64 --tag $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/amd64 -f Dockerfile .
      - docker build --platform linux/arm64 --tag $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/arm64 -f Dockerfile .

      - docker push $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/aarch64
      - docker push $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/amd64 
      - docker push $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/arm64

      - |
        docker manifest create $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME} \
        $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/amd64 \
        $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/arm64 \
        $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/aarch64
      - docker manifest annotate --arch arm64 --variant v8 $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME} $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/arm64
      - docker manifest annotate --arch amd64 $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME} $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/amd64
      - docker manifest annotate --arch aarch64 $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME} $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}/aarch64
      - docker manifest push $${DOCKER_REGISTRY_URL}/$${IMAGE_NAME}

    when:
      branch:
        - main
    volumes:
      - name: docker
        path: /var/run/docker.sock
 
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
